### ISSUE TITLE
pip install yields errors

### ISSUE THREAD

**Issue by julienchastang** [hadim/jupyter-archive#37]
```
Building wheels for collected packages: jupyter-archive
  Building wheel for jupyter-archive (setup.py): started
  Building wheel for jupyter-archive (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bjc365l5/jupyter-archive/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bjc365l5/jupyter-archive/
setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-aqm8i
2yt
       cwd: /tmp/pip-install-bjc365l5/jupyter-archive/
  Complete output (69 lines):
  running bdist_wheel
  running jsdeps
  Installing build dependencies with npm.  This may take a while...
  > npm install
  npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
  npm WARN lifecycle @hadim/jupyter-archive@0.7.0~prepare: cannot run in wd @hadim/jupyter-archive@0.7.0 yarn run clean && yarn run build (wd=/tmp/pip-install-bjc365l5/jupyter-archive)
  npm notice created a lockfile as package-lock.json. You should commit this file.
  npm WARN @lumino/coreutils@1.5.2 requires a peer of crypto@1.0.1 but none is installed. You must install peer dependencies yourself.

  added 150 packages from 1016 contributors and audited 150 packages in 10.607s

  19 packages are looking for funding
    run `npm fund` for details

  found 0 vulnerabilities

  > npm run build:all

  > @hadim/jupyter-archive@0.7.0 build:all /tmp/pip-install-bjc365l5/jupyter-archive
  > yarn run build:labextension

  yarn run v1.22.4
  $ cd jupyter_archive && rimraf labextension && mkdirp labextension && cd labextension && npm pack ../..
  npm WARN lifecycle @hadim/jupyter-archive@0.7.0~prepare: cannot run in wd @hadim/jupyter-archive@0.7.0 yarn run clean && yarn run build (wd=/tmp/pip-install-bjc365l5/jupyter-archive)
  npm notice
  npm notice 📦  @hadim/jupyter-archive@0.7.0
  npm notice === Tarball Contents ===
  npm notice 1.5kB LICENSE
  npm notice 0     style/index.css
  npm notice 1.1kB schema/archive.json
  npm notice 1.9kB package.json
  npm notice 2.8kB README.md
  npm notice === Tarball Details ===
  npm notice name:          @hadim/jupyter-archive
  npm notice version:       0.7.0
  npm notice filename:      hadim-jupyter-archive-0.7.0.tgz
  npm notice package size:  3.1 kB
  npm notice unpacked size: 7.2 kB
  npm notice shasum:        208a93becb2ecbc8754dad19bac28b378d891d5e
  npm notice integrity:     sha512-sFk9DKVARdD6a[...]ha6Ye8y9Iewzw==
  npm notice total files:   5
  npm notice
  hadim-jupyter-archive-0.7.0.tgz
  Done in 13.37s.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-bjc365l5/jupyter-archive/setup.py", line 67, in <module>
      extras_require={"test": ["jupyterlab", "pytest"]},
    File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-bjc365l5/jupyter-archive/setupbase.py", line 465, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-install-bjc365l5/jupyter-archive/setupbase.py", line 465, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-bjc365l5/jupyter-archive/setupbase.py", line 261, in run
      c.run()
    File "/tmp/pip-install-bjc365l5/jupyter-archive/setupbase.py", line 387, in run
      raise ValueError(("missing files: %s" % missing))
  ValueError: missing files: ['/tmp/pip-install-bjc365l5/jupyter-archive/lib/index.js']
  ----------------------------------------
  ERROR: Failed building wheel for jupyter-archive
```

**Comment by hadim** [comment]
Could you try installing it with conda?

**Comment by julienchastang** [comment]
I was trying this on behalf of a user that has since completed their internship so I no longer need this functionality, at least in the immediate term. I'll leave this issue open, however, as other users may run into the same issue.

**Comment by hadim** [comment]
Thank you @julienchastang and sorry for the delay then.

I am not very active here anymore since I am waiting to integrate this extension within Jupyter directly: https://github.com/jupyter/jupyter_server/pull/252

**Comment by hadim** [comment]
See https://github.com/hadim/jupyter-archive/issues/40

**Comment by fcollonval** [comment]
The error is:
```
cannot run in wd @hadim/jupyter-archive@0.7.0 yarn run clean && yarn run build (wd=/tmp/pip-install-bjc365l5/jupyter-archive)
```

I had similar problem when running node within a Docker that was not using a non-root user; npm will decrease it is rights (by default it switches to `nobody`). You can change through the `unsafe-perm` configuration parameter: https://docs.npmjs.com/cli/v6/using-npm/config#unsafe-perm.

Note: we need to distribute the package as wheel to ease the life of the users.
